export {default as Navbar} from './Navbar'
export {default as Cryptocurrencies} from './Cryptocurrencies'
export {default as CryptDetails} from './CryptDetails'
export {default as Homepage} from './Homepage'
export {default as Exchanges} from './Exchanges'
export {default as News} from './News'